language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit --coverage-clover=coverage.xml

before_install:
  - pip install --user codecov
after_success:
  - codecov
