language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - php composer.phar install
  - phpunit --coverage-clover=coverage.xml

before_install:
  - pip install --user codecov
after_success:
  - codecov

notifications:
  slack: lenddo:iJYeCC5sZSx2A0BW5dvgZiBe
